#!/bin/sh

git status > /dev/null
if [ $? -eq 0 ]
then
    desc=`git describe | sed 's/^v//'`
    branch=`git symbolic-ref HEAD | grep -o '[[:alpha:]]\+$'`
    if [ "$branch" != "master" ]
    then
        V=$desc-$branch
    else
        V=$desc
    fi
else
    V="unknown"
fi

echo $V

